version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: todjom_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todjom_market_db
      MYSQL_USER: todjom_user
      MYSQL_PASSWORD: todjom_password
      MYSQL_ROOT_PASSWORD: root_secure_password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - todjom

  backend:
    build:
      context: ./backend
    container_name: todjom_backend
    working_dir: /var/www
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - todjom

  frontend:
    build:
      context: ./frontend
    container_name: todjom_frontend
    command: npm run build
    volumes:
      - frontend_build:/app/build
    restart: "no"

volumes:
  dbdata:
  frontend_build:

networks:
  todjom:
    driver: bridge